### ISSUE TITLE
Is jsc cross-platform?

### ISSUE THREAD

**Issue by wll8** [OsamaAbbas/bytenode#101]
I compiled a simple js file on macos. But the generated jsc file cannot run in win7x64. The node version used is the same.

I need to use the source code to recompile on win7 in order to run on win7.

So I have a question, is jsc cross-platform?

**Comment by OsamaAbbas** [comment]
From README.md:

> Please note `.jsc` files must run with the same Node.js version that was used to compile it (using same architecture of course). Also, `.jsc| files are CPU-agnostic. However, you should run your tests before and after deployment, because V8 sanity checks include some checks related to CPU supported features, so this may cause errors in some rare cases.

So it is NOT cross-platform. Not even cross-Node.js-versions.

**Comment by christopherGr** [comment]
The solution that I have found in order to compile .js files with bytenode, from a windows machine with arch **x64**, for arch **ia32**,
is to create a new help application with electron with arch ia32, that its goal is to compile files. The filepaths are passing as arguments to the exe when it is running through cmd. I beleive that this may be accomplished also with nexe and pkg. If everyone needs I can give more info.

However I cannot find solution in order to complie .js files from a windows machine for a mac. 
If anyone has any suggestion I would appreciate it!

**Comment by j4k0xb** [comment]
https://github.com/v8/v8/commit/6cb174b4b3c11c566be55434bdcf82f8a9ec47c8#diff-69dd3fc57a86fdc6d207c04dcc49385398a5de2a43c59ac35064755a8635f0d5

CPU feature checks have been removed years ago but it's still not possible to run jsc on Linux that was built on Mac or Windows (even when both are 64-bit).
Do these have different v8 flags that somehow mess with how the data is serialized/deserialized?

**Comment by OsamaAbbas** [comment]
> [v8/v8@6cb174b#diff-69dd3fc57a86fdc6d207c04dcc49385398a5de2a43c59ac35064755a8635f0d5](https://github.com/v8/v8/commit/6cb174b4b3c11c566be55434bdcf82f8a9ec47c8#diff-69dd3fc57a86fdc6d207c04dcc49385398a5de2a43c59ac35064755a8635f0d5)
> 
> CPU feature checks have been removed years ago but it's still not possible to run jsc on Linux that was built on Mac or Windows (even when both are 64-bit). Any idea why?

If I remember correctly: if you try to ignore bytenode's checks and run the file anyways (even on the same OS but with different Node.js version), the whole application would crash unexpectedly, not from within Node.js, but from the C++ side. So, you cannot even handle the error.

I will re-try again, although I don't think the result will be any different.
