### ISSUE TITLE
bytenode child process fork with message passing not working

### ISSUE THREAD

**Issue by Vishal8523** [OsamaAbbas/bytenode#103]
There are 2 bytenode executables - one is parent and another is child.

When parent is calling the child, the child process is getting started. However, the messages sent by the parent process are never received by the child.

For example, this is what I was trying:
**parent.js**
```
var path = require('path');
var cp = require('child_process');

var child = cp.fork(path.join(__dirname, './child.jsc'), {
    execPath: `bytenode`
});

child.send('Hello Child');

child.on('message', function (result) {
    console.log('Message from Child: ', result);
});
```

**child.js**
```
console.log('Child process started');

process.on('message', function (parentMessage) {
    console.log('Child process received message: ', parentMessage);
});

process.send('Hello from Child');
```

Appreciate your help.

**Comment by OsamaAbbas** [comment]
This is due to how `bytenode` executable is implemented, which is based on spawning another process. So, when you use `bytenode` as the `execPath`, what happens is that `bytenode` is the real parent process. Also, due to how the `procss.send` function is implemented, you will end up with your situation.

The workaround is easy though, instead of using `execPath: \`bytenode\``, use this instead:

```javascript
var child = cp.fork(path.join(__dirname, './child.jsc'), {
  execArgv: ['-r', path.join(__dirname, 'node_modules', 'bytenode')]
});
```

That way, the `node` executable will be used as usual, but it will load `bytenode` before it execute your `child.jsc`.

Don't forget to install `bytenode` locally of course.

I tested your code and it worked with both Node v14 and v15. So I will close this issue as solved.

If you have any further question feel free to ask.

**Comment by Vishal8523** [comment]
Thanks @OsamaAbbas for the help.
Awesome. It works. :)
