### ISSUE TITLE
object.property?.method() syntax

### ISSUE THREAD

**Issue by GirkovArpa** [OsamaAbbas/bytenode#118]
I saw this in `index.js`:

```javascript
proc.stdin?.write(javascriptCode);
```

I was wondering what the purpose is, because it seems to be a shortcut to ignore the case where the method `write` doesn't exist, but executing this in my browser console throws an error anyway:

```javascript
window?.write();
```
> Uncaught TypeError: window?.write is not a function

I would imagine that if `stdin` did not have a method `write` then it would throw a similar error.  So I am intrigued!

**Comment by OsamaAbbas** [comment]
When you use the `?`, you guard the object itself, so that if it was `null` or `undefined`, nothing is thrown. Once your code pass that guard (i.e. the object is already there), nothing will guard you against a bad call (i.e. calling a non-existent function).

So, `window?.write()` is not equivalent to `proc.stdin?.write()`. That is because we know that `stdin` has the `write()` function.

The error you get with `window?.write()` is equivalent to if someone tried to do `proc.stdin?.playMusic()`.

If you want to guard against the method, do something like this: `window.write?.()`, or `proc.stdin.playMusic?.()`.

**Comment by GirkovArpa** [comment]
Wow thanks!  Did not know that `window.write?.()` was valid syntax.  I am still trying to understand what you mean about `proc.stdin?.write()` though.

**Comment by OsamaAbbas** [comment]
As for the `proc.stdin?.write()` thing:

Imagine if we wrote something like this `proc.stdin.yyy` or `proc.stdin.zzz()`, what would happen if `proc` does not have `stdin` (i.e. `proc.stdin` is `undefined` or `null`)? This line will throw an error, because we are trying to access a property or a function on a non-existent object. The program will crash then.

How could we solve this issue?

In the old days, you would have to do something like this:

```javascript
if (proc.stdin !== null && proc.stdin !== undefined) {
  proc.stdin.yyy;
  proc.stdin.zzz(); // assuming that zzz is a function.
}
```

With the new syntax, all you need to do is `proc.stdin?.yyy` and `proc.stdin?.zzz()`. And if you want to take care of the scenario where you are not sure that `stdin` has a function called `zzz()`, you will write `proc.stdin?.zzz?.()`;
