### ISSUE TITLE
Can't make it work executing inside .js file

### ISSUE THREAD

**Issue by robot110011** [OsamaAbbas/bytenode#16]
I'm trying to run those:

`main.js`

```
let myModule = require('./code.jsc');
myModule.print();
```

`code.js`

```
module.exports = {
	print(){
		console.log('works!');
	}
};
```

It works when I use `bytenode code.jsc` directly but doesn't work when I use `node main.js` (output nothing)

I compiled with the following command:
`bytenode -c code.js`

Am I missing something?

Platform: Mac OS

**Comment by OsamaAbbas** [comment]
You have to require `bytenode` first somewhere in your code. Otherwise, node's `require` function wouldn't know how to require `.jsc` extension nor these files.

So, in your `main.js` file, add this line first: `require('bytenode');` so that the `jsc` extension gets registered in and understood by node require system.

If, for some reason, you don't have the choice to add that line, then you have to run node like this: `$ node -r bytenode main.js`.

**Comment by robot110011** [comment]
Makes sense, thanks it worked.
If I plan to use in an electron app , is there any recommendation to not break it? or just need to compile renderer and it's done?

**Comment by OsamaAbbas** [comment]
You can use bytenode wherever the node's `require` function is defined and can be used.

However, check issue #10, if you want to use `Buffer` in your app.
