### ISSUE TITLE
Does *.jsc file is safe?

### ISSUE THREAD

**Issue by soloroman** [OsamaAbbas/bytenode#17]
I am newbie at it, so dont judge plz.
How shold i know if *.jsc could be decompiled?
Does it really hide sourcecode of my app? Because i have tried many ways to protect it in WASM, PKG (npm), etc...
PKG creates binary file, which i can read by simple notepad and find pure JS. So it hides code a bit.

**Comment by OsamaAbbas** [comment]
In this sense, bytenode creates V8 bytecode files, which could be de-compiled theoretically, but this was never done before, and it is unlikely to be done unless there is a very urgent demand for it so that some hackers will try to reverse-engineer it.

What makes it worse for the hacker and better for us, is that the V8 API is changing quickly, and in many cases, it lacks docs and resources that explain what is going on.

So, your question can be answered with "yes, for all practical purposes". At least for now and the foreseeable future.
