### ISSUE TITLE
Error with node 13.0.1

### ISSUE THREAD

**Issue by cfal** [OsamaAbbas/bytenode#35]
I have a project that packages with bytenode before deployment. Unfortunately with node 13.0.1, I'm seeing a new error:
$ bytenode app.jsc
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

This is happening when creating the vm.Script object: https://github.com/OsamaAbbas/bytenode/blob/master/index.js#L91-L93

**Comment by OsamaAbbas** [comment]
When node 13 was released I tested it out with a simple `hello world` example. Appareantly this is not enough.

I will look into this issue. I guess I know its cause, but if you have a minimal example that reproduce the error it'd help.

**Comment by OsamaAbbas** [comment]
I can reproduce the error, using the `express-hello-world` example but only if the whole server is bundled using browserify (see this README for details).

However, the same error occurs in Node 12 too. So either this is another issue that happens in both node 12 and 13, or it is the same issue as yours. I need you to try out the same setup with node 12, so that we see if node 12 will reproduce it or not.

And still investigating to find a fix.

**Comment by OsamaAbbas** [comment]
Please update to `bytenode 1.1.2`.

```bash
$ sudo npm install --global bytenode
```

Let me know if this version fixes your issue.

**Comment by cfal** [comment]
That fixed it. Thanks for the quick response!
