### ISSUE TITLE
Thoughts about bytecode flushing

### ISSUE THREAD

**Issue by ajihyf** [OsamaAbbas/bytenode#36]
Thanks for your inspiring project 👍.

I have a question about implementation. Currently, a dummy source string is used to instantiate `vm.Script`. However, V8 docs(https://v8.dev/blog/v8-release-74#bytecode-flushing) says

>  Any bytecode which crosses an aging threshold is eligible to be collected by the next garbage collection, and the function resets to lazily recompile its bytecode if it is ever executed again in the future.

It seems that V8 lazily recompiles a function's source string if it is executed after its bytecode is garbage collected. Will the dummy string make a potential bug because of the bytecode-flushing technique?

**Comment by OsamaAbbas** [comment]
First of all, as you already know that we are [ab]using the caching mechanism in a way that was not intended by v8 or Node.js developers. So, there is no guarantee that bytenode will continue to work with the continues changes in either v8 or Node.js.

Second, with regards to your specific concern, I guess that our cached bytecode is safe from being garbage collected, because we turn off the lazy compiling altogether. I'm not 100% sure though because I have not looked into this part in the v8 source code in depth.

Thank you for your question and kind words.

**Comment by ajihyf** [comment]
Thanks for instant reply. I've checked the [v8 source code](https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/objects/shared-function-info-inl.h#L501), turning off lazy compilation should be safe

```cpp
bool SharedFunctionInfo::ShouldFlushBytecode(BytecodeFlushMode mode) {
  if (mode == BytecodeFlushMode::kDoNotFlushBytecode) return false;

  if (IsResumableFunction(kind()) || !allows_lazy_compilation()) {
    return false;
  }
  ...
}
```

There are also `--no-flush-bytecode` and  `--no-stress-flush-bytecode` flags to disable bytecode flushing. Though [ab]using v8 flags may not be descent, it should solve the problem now. Looking forward to the v8 team releasing a production-ready way to run bytecode directly.
