### ISSUE TITLE
unable to execute /bin/bytenode: Argument list too long

### ISSUE THREAD

**Issue by omarkanawati** [OsamaAbbas/bytenode#45]
Hello, Appreciate your advice.

When trying the following command `sudo bytenode --compile ../projectName/**/*.js` i get the stated error "unable to execute /bin/bytenode: Argument list too long"

Note: project node modules are included and when trying without them, I get an error of "cannot find express module" when running the project .jsc

Node Version: 10.0.0
Environment: RedHat 7 server

**Comment by OsamaAbbas** [comment]
For the first issue "Argument list too long":

This is a bash limitation.

You can use either:

```console
$ find . -type f -name "*.js" -exec bytenode --compile {} +
```

or:

```console
$ for js_file in ./**/*.js; do bytenode --compile "$js_file"; done
```

However, you should NOT compile your `node_modules` as it usually contains too many files, and there is no real need to compile them all. So maybe you want to copy your code to a `./dist` folder first, then you compile them using bytenode, then you delete all `./dist/**/*.js` files.

Otherwise you might want to use `browserify` to bundle you project first:

```console
$ [sudo ] npm install -g browserify
$ browserify --node server.js > bundle.js
$ bytenode --compile bundle.js
```

See this [example](https://github.com/OsamaAbbas/bytenode/tree/master/examples/express-hello-world).

But again, I recommend that you compile only you own code.

Let me know if this answers your question. Feel free to reopen the issue if needed.

**Comment by omarkanawati** [comment]
Thank you for your prompt and detailed reply.
It helped me alot and i was able to compile the project code only.
As for browserify, i tried it, following your example but it requires some dependencies that i'm trying to avoid so i will settle with the first solution.
Thanks again.
