### ISSUE TITLE
Error: unrecognized flag --no-flush-bytecode

### ISSUE THREAD

**Issue by s100** [OsamaAbbas/bytenode#48]
Regrettably it looks as if the fix introduced for issue #41 - setting the V8 flag, `--no-flush-bytecode` - has made it so that `bytenode` can no longer be loaded on earlier versions of Node.js where this flag does not exist. In our case:

```sh
nvm use 10.16.3
npm install bytenode
node -e "require('bytenode')"
```

outputs:

```
Error: unrecognized flag --no-flush-bytecode
Try --help for options
```

This occurs with `bytenode@1.1.3` onwards. Pinning to `bytenode@1.1.2` resolves the issue. Upgrading to Node.js 12.10.0 also resolves it.

Unfortunately V8's flags are exceedingly poorly documented and I'm not aware of any API for listing the flags so we can check whether the flag exists before trying to set it...

**Comment by OsamaAbbas** [comment]
Thank you for your reporting.

We can fix it using `if node version > xx.xx` statement, or using `try .. catch` statement. I tend to prefer the latter because it's easy, but I need another vote before choosing it :) .

> I'm not aware of any API for listing the flags so we can check whether the flag exists before trying to set it...

Yes, there is no API for that. However, you can run `node --v8-options` to get that list.

**Comment by s100** [comment]
`try .. catch` seems as good a solution as any to me.
