### ISSUE TITLE
Is the bytecode generated arch independent?

### ISSUE THREAD

**Issue by PatriceJiang** [OsamaAbbas/bytenode#59]
Can I running the bytecode which generated by windows/x86  on Android/ARM?

**Comment by OsamaAbbas** [comment]
From the README file:

> Please note .jsc files must run with the same Node.js version that was used to compile it (using same architecture of course).

So, you can't.

**Comment by PatriceJiang** [comment]
Thanks

**Comment by mattiapv** [comment]
Hello @OsamaAbbas I'm currently using pkg to make executables. I'm on macOS and I create packages for Windows and Linux. On the README they also write "If you want to generate executable for different architectures, note that by default pkg has to run the executable of the target arch to generate bytecodes" But I've used pkg unpacker and I found that the source is in bytecode. Do you know how they are able to generate bytecode for windows from macOS? I'm trying to switch from pkg and use caxa+bytenode.
Thanks!

**Comment by OsamaAbbas** [comment]
> Do you know how they are able to generate bytecode for windows from macOS?

This is not possible. Not in bytenode nor in pkg or any other libraries. Bytecodes has to be generated using the exact same arch that will run in production.

It's painful but you have to do it that way.

> I've used pkg unpacker and I found that the source is in bytecode.

I don't use pkg so I have no experience with it, but maybe they have an option to remove the source from your binaries?

> I'm trying to switch from pkg and use caxa+bytenode.

Bytenode will remove the source code, yes. But you have to generate bytecodes using different architectures still.

**Comment by mattiapv** [comment]
> I don't use pkg so I have no experience with it, but maybe they have an option to remove the source from your binaries?

I don't know maybe is not bytecode what they generate. I used this simple code:

```js
var bytecode = 'Bytecode';

console.log(bytecode);
```
I created the package with pkg, unpacked and opened on an Hex editor because vscode showed this message "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding"
![Screenshot 2022-12-15 at 02 12 47](https://user-images.githubusercontent.com/28735046/207750009-7274e3cf-6ead-4d43-8c7e-61dcf5cdfa76.png)

pkg logs
```
> [debug] The file was included as bytecode (no sources)
  /Users/Mattia/Desktop/bytenode/build/index.js
 ```

Using bytenode I got this
![Screenshot 2022-12-15 at 02 08 01](https://user-images.githubusercontent.com/28735046/207750383-7b3236ef-26b2-49f7-8aaa-ef776a0a81d5.png)

Running pkg with the option `--no-bytecode` I got the original code when unpacked and I was able to open it on vscode.

The both .exe are working on windows.

Anyway I was just curios if there is a way to avoid using something like Github Actions to run build on different arch, but as you said is not possible.

**Comment by OsamaAbbas** [comment]
Finding glimses  of your original code (e.g. variables' and classes' names) inside a binaries does not mean that the code in unprotected. Especially for string values. You will find them exposed even in compiled c and c++ binaries.

So, you should never use bytenode (or pkg, or even c language) tp hide something like this:

```
const my_top_secret_key = '... etc';
```

That being said, both pkg and bytenode are doing as well from your screenshots.
