### ISSUE TITLE
Error while packaging with pkg

### ISSUE THREAD

**Issue by pleum** [OsamaAbbas/bytenode#72]
```shell
> pkg@4.4.9
> Targets not specified. Assuming:
  node14-linux-x64, node14-macos-x64, node14-win-x64
> Error! Unexpected character '�' (1:0)
  F:\testbytenode\main.jsc
```
Is there any example to use bytenode with pkg?

**Comment by OsamaAbbas** [comment]
Never tested it before. I will look into it and get back to you whether it can be done or not.

**Comment by OsamaAbbas** [comment]
From `pkg` README.md file:

> # Assets
> `assets` is a glob or list of globs. Files specified as `assets` will be packaged into executable as raw content without modifications. Javascript files may also be specified as `assets`. Their sources will not be stripped as it improves execution performance of the files and simplifies debugging.

Read their README.md file as they explain how could you define your assets.

If I managed to try it myself, I will post an update here.

**Comment by pleum** [comment]
I already put compiled scripts to assets folder and give me same error, I thought It try to read 'require(..)' for package all module dependency in single executable.

**Comment by OsamaAbbas** [comment]
OK, here is how you could do it.

1. Run `pkg .` (after installing it) and check which version it will fetch. For example:

```
osama@asus: $ pkg .
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.18.1-linux-x64   [====================] 100%
```

2. Install that exact version of node `12.18.1`. I'm using [`n` script](https://www.npmjs.com/package/n), so:
```
osama@asus: $ sudo n 12.18.1
[sudo] password for osama:    

  installing : node-v12.18.1
       mkdir : /usr/local/n/versions/node/12.18.1
       fetch : https://nodejs.org/dist/v12.18.1/node-v12.18.1-linux-x64.tar.xz
   installed : v12.18.1 (with npm 6.14.5)
```

3. Now, run your project as usual, so that all `.jsc` are generated. I'm using a simple `index.js` file that goes like this:

```javascript
'use strict';

const fs = require('fs');
const bytenode = require('bytenode');

if (!fs.existsSync('./server.jsc')) {
  bytenode.compileFile('./server.js', './server.jsc');
}

let requireJSC = require;

requireJSC('./server.jsc'); // we do this in order to trick pkg so it won't try to resolve the file
```

4. Add `"**/*.jsc"` to your `assets`, so your `package.json` would be something like that:

```json
{
  "name": "express-example",
  "license": "ISC",
  "bin": "index.js",
  "dependencies": {
    "bytenode": "^1.1.6",
    "express": "4.15.2"
  },
  "pkg": {
    "assets": [
      "views/**/*",
      "**/*.jsc"
    ],
    "targets": [
      "node12"
    ]
  }
}
```

5. Now, run `pkg .` to package your project.

It should work now.

I'm closing this issue now. If your problem persists, feel free to ask.
