### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by garosi** [OsamaAbbas/bytenode#78]
Hello! I used bytenode in my project , but now after update and building app with electron-builder I getting error.
![Безымянный](https://user-images.githubusercontent.com/61659338/94568428-229bd800-0275-11eb-994e-46ded00532e0.png)

**Comment by OsamaAbbas** [comment]
Please provide a minimal setup and project with electron-builder, that reproduce this error.

Don't expect that I have experience with electron and its tools. I need a reproducible example to check where the issue lies.

**Comment by pedro-surf** [comment]
I think it's due to [that issue](https://github.com/OsamaAbbas/bytenode/issues/73), seems like the source must be compiled at same runtime than build is generated. Perhaps you could try to erase your previous version `.jsc` when unpacking the update. If you could provide a simple repo with the updater it would be great, I'm struggling with that too.

**Comment by garosi** [comment]
Problem was in difference between electron global version and electron project version .
