### ISSUE TITLE
Bytenode causes error with Electron

### ISSUE THREAD

**Issue by SentoxAIO** [OsamaAbbas/bytenode#87]
I am compiling parts of my electron app with Bytenode but it fails loading those compiled files.

I compile the files before packing the electron app.
When the app gets executed and the files loaded, it throws this error:

![image](https://user-images.githubusercontent.com/57367608/99858090-0b021100-2b8d-11eb-86ee-050ce26f0436.png)

To compile I use the Bytenode CLI with the following command:

`globstar --node -- bytenode -c <file path>`

### What I already tried to fix it: 

I already tried `globstar --node -- bytenode --no-modules <file path>` before but this one doesn't work since the flag doesn't exist in node 14.x.x

`globstar --node -- bytenode --no-flush-bytecode <file path>` doesn't work as well and throws this error:
![image](https://user-images.githubusercontent.com/57367608/99859636-e1e37f80-2b90-11eb-828b-f2c0899e0c03.png)

**Comment by OsamaAbbas** [comment]
As explained many times before, you must compile your files using electron itself (check our electron example), in order to run them in electron.

When you compile them using bytenode cli, this means that you compiled them for node.js environment, not electron. They will not even work with another version of node.js. The compiled files are version, arch, platform and binary specific.
