### ISSUE TITLE
Error: Invalid or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by connorstevens** [OsamaAbbas/bytenode#96]
I am building a Node.JS Application and using Bytenode for security. I am using pkg from Vercel to build it into an executable file. Obfuscating with basic RC4 encryption works well. The executable that pkg produces works well. When I use bytenode, it does not run.

```C:\Users\user\Documents\Development\project\bytenode>project.exe
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Invalid or incompatible cached data (cachedDataRejected)
    at Object..jsc (C:\snapshot\user\Documents\Development\project\node_modules\[4mbytenode[24m\index.js:195:11)
```
    
My project is structured like this:
![image](https://user-images.githubusercontent.com/25255502/103965410-a3e3f000-512b-11eb-9329-b5df2dcafc97.png)

This is my PKG config:

`
"bin": "test.js",
"pkg": {
    "assets": [
      "utils/**.jsc",
      "modules/**.jsc",
      "index.jsc"
    ],
    "targets": [
      "node12"
    ]
  }`

I appreciate any help you can offer. Thanks!

**Comment by OsamaAbbas** [comment]
This is due to the difference in the binaries between the installed version of node.js on your machine, and the version that `pkg` has used to bundle your app.

To solve this problem, you have to use the exact version of node.js to generate the `.jsc` files.

So, for example, you can put `console.log(process.versions.node);` on the top of your very first file. Then, package it using the same pkg config (e.g. `[ "node12" ]`. Now you will know which version exactly is used, so install it using `nvm` or `n` (e.g. `sudo n 12.18.1`). Regenerate your `.jsc` files and package the project again.

An example setup that works with the previous steps: [issue-96.zip](https://github.com/OsamaAbbas/bytenode/files/5786355/issue-96.zip)
